language: ruby
rvm:
  - 2.3

gemfile:
  - gemfiles/gemfile.rails52
  - gemfiles/gemfile.rails42
  - gemfiles/gemfile.rails41
  - gemfiles/gemfile.rails40

notifications:
  irc: "irc.freenode.org#projecthydra"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
