language: ruby
rvm:
  - 2.5
  - 2.4

gemfile:
  - gemfiles/gemfile.rails52
  - gemfiles/gemfile.rails42

notifications:
  irc: "irc.freenode.org#projecthydra"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
